name: Deploy Gradle Plugin

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set version
        run: echo "VERSION_NAME=${GITHUB_REF#refs/*/}" >> gradle.properties

      - name: Append variables
        run: |
          echo "mavenCentralUsername=$OOSRH_USERNAME" >> gradle.properties
          echo "mavenCentralPassword=$OOSRH_PASSWORD" >> gradle.properties
          echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties
          echo "signing.password=$SIGNING_PASSWORD" >> gradle.properties
          echo "signing.secretKeyRingFile=$SIGNING_SECRET_RING" >> gradle.properties
        env:
          OOSRH_USERNAME: ${{ secrets.OOSRH_USERNAME }}
          OOSRH_PASSWORD: ${{ secrets.OOSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}

      - name: Create secring.gpg file
        run: |
          mkdir -p $SIGNING_SECRET_RING
          rmdir $SIGNING_SECRET_RING
          printf "$SIGNING_SECRET_RING_FILE" | base64 --decode > $SIGNING_SECRET_RING
        env:
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}
          SIGNING_SECRET_RING_FILE: ${{ secrets.SIGNING_SECRET_RING_FILE }}

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build Library
        run: ./gradlew --no-daemon :dragapult-gradle:assemble

      - name: Publish Library
        run: ./gradlew --no-daemon --no-parallel :dragapult-gradle:publish

      - name: Release Library
        run: ./gradlew --no-daemon --no-parallel :dragapult-gradle:closeAndReleaseRepository
